apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-producer
  namespace: fb-crawler-apps
  labels:
    component: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskQueue
      component: producer
  template:
    metadata:
      labels:
        app: taskQueue
        component: producer
    spec:
      containers:
        - name: producer
          image: bhonebhone/fb-producer:v1
          env:
            - name: FBS_DATABASE_POSTGRESQL_SERVICE_HOST
              value: postgresql://fbs:yah7WUy1Oi8G@192.168.11.202:5432/fbs
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
